name: CI build

on:
  push:
    branches: [ "master", "3.0.0-rebase" ]
  pull_request:
    branches: [ "master", "testing" ]

jobs:
  build:
    name: Ubuntu (Clang)
    runs-on: ubuntu-latest
    steps:
      - name: Clone DOVI
        uses: GuillaumeFalourd/clone-github-repo-action@v2.3
        with:
          owner: 'quietvoid'
          repository: 'dovi_tool'

      - name: Clone HDR10+
        uses: GuillaumeFalourd/clone-github-repo-action@v2.3
        with:
          owner: 'quietvoid'
          repository: 'hdr10plus_tool'
          
      - name: Compile Cargo
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: |
          cd dovi_tool
          cargo install cargo-c
          cargo cinstall --release .
          cd ..
          cd hdr10plus_tool
          cargo install --path .
      - uses: actions/checkout@v4
      - uses: ilammy/setup-nasm@v1
      - run: git fetch --prune --unshallow
      - name: Ubuntu/Mac OS X
        run: |
          cd Build/linux
          ./build.sh jobs=$(nproc) cc=clang cxx=clang++ enable-lto static native
      - name: Test
        uses: actions/upload-artifact@v4
        with:
          name: SvtAv1EncApp
          path: /home/runner/work/svt-av1-psy/svt-av1-psy/Bin/Release/SvtAv1EncApp
