name: CI build

on:
  push:
    branches: [ "master", "3.0.0-rebase" ]
  pull_request:
    branches: [ "master", "testing" ]

jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - {
              name: "Windows MSVC 64 Bit",
              os: windows-2022,
              environment_script: "C:/Program Files/Microsoft Visual Studio/2022/Enterprise/VC/Auxiliary/Build/vcvars64.bat",
              generators: "Visual Studio 17 2022",
              msvc_arch: x64
            }
          - {
              name: "Ubuntu Latest",
              os: ubuntu-latest,
              c_compiler: gcc,
              cpp_compiler: g++,
            }
          - {
              name: "Ubuntu Latest (Clang)",
              os: ubuntu-latest,
              c_compiler: clang,
              cpp_compiler: clang++,
            }
          - {
              name: "Mac OS Latest arm64",
              os: macos-latest,
              c_compiler: clang,
              cpp_compiler: clang++,
              osx_arch: arm64
            }
    env:
      CMAKE_GENERATOR: "${{ matrix.config.generators }}"
    steps:
    - uses: actions/checkout@v4
    - uses: ilammy/setup-nasm@v1
    - run: git fetch --prune --unshallow
    - name: Ubuntu/Mac OS X
      if: ${{ !contains( matrix.config.generators, 'Visual Studio' ) }}
      run: |
        cd Build/linux
        ./build.sh jobs=$(nproc) cc=clang cxx=clang++ enable-lto static native
    - name: Test
      uses: actions/upload-artifact@v4
      with:
        name: SvtAv1EncApp
        path: /home/runner/work/svt-av1-psy/svt-av1-psy/Bin/Release/SvtAv1EncApp
    - name: MSVC build
      if: contains( matrix.config.generators, 'Visual Studio' )
      run: |
        cmake -B Build -A "${{ matrix.config.msvc_arch }}" -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=ON -DBUILD_APPS=ON -DBUILD_DEC=OFF -DREPRODUCIBLE_BUILDS=ON
        cmake --build Build --config Release
      shell: cmd
