name: CI build

on:
  push:
    branches: [ "master", "testing-bob-mimalloc" ]
  pull_request:
    branches: [ "master", "testing" ]

jobs:
  build:
    name: Ubuntu Latest (Clang)
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ilammy/setup-nasm@v1
    - uses: egor-tensin/setup-clang@v1
      with:
        version: latest
        platform: x64
    - uses: jlumbroso/free-disk-space@main
      with:
        # this might remove tools that are actually needed,
        # if set to "true" but frees about 6 GB
        tool-cache: true
        
        # all of these default to true, but feel free to set to
        # "false" if necessary for your workflow
        android: true
        dotnet: true
        haskell: true
        large-packages: false
        docker-images: true
        swap-storage: true
    - run: git fetch --prune --unshallow
    - name: Ubuntu/Mac OS X
      run: |
        mkdir IRpgo
        cmake --fresh -B Build -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_C_COMPILER=clang -DNATIVE=OFF -DENABLE_AVX512=ON -DCMAKE_CXX_FLAGS_RELEASE="-DNDEBUG -O2 -march=znver2 -flto=thin -ffast-math -stdlib=libc++ -fprofile-generate=IRpgo" -DCMAKE_C_FLAGS_RELEASE="-DNDEBUG -O2 -march=znver2 -flto=thin -ffast-math -fprofile-generate=IRpgo" -DSVT_AV1_LTO=ON -DBUILD_APPS=ON
        cmake --build Build --config Release
      shell: bash
    - uses:  GuillaumeFalourd/clone-github-repo-action@v2.3
      with:
        depth: 1
        branch: 'main'
        owner: 'EdgeLord69-dev'
        repository: 'pgo'
    - name: IR PGO
      run: |
        cd pgo
        sudo apt update && sudo apt update -qq && sudo apt upgrade
        sudo apt install python3 python3-pip ffmpeg
        curl -O https://media.xiph.org/video/derf/objective-2-fast.tar.gz
        tar -xvf objective-2-fast.tar.gz
        rm -rf objective-2-fast.tar.gz
        python3 encode.py --svt-repo ../
        rm -rf objective-2-fast
        cd ..
        ls IRpgo
        llvm-profdata merge IRpgo/*.profraw -output=IR.profdata
      shell: bash

    - name: CSIR PGO
      run: |
        mkdir CSIRpgo
        cmake --fresh -B Build -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_C_COMPILER=clang -DNATIVE=OFF -DENABLE_AVX512=ON -DCMAKE_CXX_FLAGS_RELEASE="-DNDEBUG -O2 -march=znver2 -ffast-math -stdlib=libc++ -fprofile-use="IR.profdata -fcs-profile-generate="CSIRpgo"" -DCMAKE_C_FLAGS_RELEASE="-DNDEBUG -O2 -march=znver2 -ffast-math -fprofile-use="IR.profdata -fcs-profile-generate="CSIRpgo"" -DSVT_AV1_LTO=OFF -DBUILD_APPS=ON
        cmake --build Build --config Release
        cd pgo
        curl -O https://media.xiph.org/video/derf/objective-2-fast.tar.gz
        tar -xvf objective-2-fast.tar.gz
        rm -rf objective-2-fast.tar.gz
        python3 encode.py --svt-repo ../
        rm -rf objective-2-fast
        cd ..
        ls CSIRpgo
        llvm-profdata merge CSIRpgo/*.profraw IR.profdata -output=CSIR.profdata

    - name: Build Final binary
      run: |
        cmake --fresh -B Build -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_C_COMPILER=clang -DNATIVE=OFF -DENABLE_AVX512=ON -DCMAKE_CXX_FLAGS_RELEASE="-DNDEBUG -O2 -march=znver2 -flto -ffast-math -stdlib=libc++ -fprofile-use="CSIR.profdata"" -DCMAKE_C_FLAGS_RELEASE="-DNDEBUG -O2 -march=znver2 -flto -ffast-math -fprofile-use="CSIR.profdata"" -DSVT_AV1_LTO=OFF -DBUILD_APPS=ON
        cmake --build Build --config Release
        
        
      
      
