name: CI build

on:
  push:
    branches: [ "master", "3.0.0-rebase" ]
  pull_request:
    branches: [ "master", "testing" ]

jobs:
  build:
    name: Ubuntu (Clang)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ilammy/setup-nasm@v1
      - run: git fetch --prune --unshallow

      - name: Compile cargo-c
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
      - run: cargo install cargo-c

      - name: Clone DOVI
        uses: GuillaumeFalourd/clone-github-repo-action@v2.3
        with:
          owner: 'quietvoid'
          repository: 'dovi_tool'

      - name: Compile DOVI
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
      - run: |
          cd dovi_tool/dolby_vision
          sudo -E env PATH=$PATH cargo cinstall --release

      - name: Clone HDR10+
        uses: GuillaumeFalourd/clone-github-repo-action@v2.3
        with:
          owner: 'quietvoid'
          repository: 'hdr10plus_tool'

      - name: Compile HDR10+
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
      - run: |
          cd hdr10plus_tool/hdr10plus
          sudo -E env PATH=$PATH cargo cinstall --release
          
      - name: Ubuntu/Mac OS X
        run: |
          cd Build/linux
          ./build.sh jobs=$(nproc) cc=clang cxx=clang++ enable-lto static native enable-hdr10plus enable-dovi
      - name: Test
        uses: actions/upload-artifact@v4
        with:
          name: SvtAv1EncApp
          path: /home/runner/work/svt-av1-psy/svt-av1-psy/Bin/Release/SvtAv1EncApp
